### ISSUE TITLE
Bugged in current Rust version

### ISSUE THREAD

**Issue by Bertus-W** [Arcterus/rget#4]
```
error[E0283]: type annotations required: cannot resolve `std::string::String: std::convert::AsRef<_>`
   --> C:\Users\Bertus\.cargo\registry\src\github.com-1ecc6299db9ec823\pbr-1.0.0-alpha.1\src\pb.rs:363:64
    |
363 |                         base = base + repeat!(self.bar_current.as_ref(), curr_count - 1) +
    |                                                                ^^^^^^

error: aborting due to previous error(s)

error: Could not compile `pbr`.
```

**Comment by gbip** [comment]
@Arcterus Do you plan to still maintain this ?

**Comment by Arcterus** [comment]
Yeah, sorry.  I haven't had too much time to work on my projects lately. :/

It looks like there's a new version of `pbr` which should fix this issue, so I'll try pushing an update in the next couple of days.

**Comment by gbip** [comment]
Thanks, I tried to push straight to an other branch, but everything is protected, I did not have the motivation to make a PR.

**Comment by Arcterus** [comment]
This should be fixed now.  Also yeah I think it'd be a bit of a problem if anyone could just push straight to my repository (lol).
